services:
    php:
        build:
            context: .
            target: prod # Ou dev pour local
        environment:
            APP_ENV: prod
            DATABASE_URL: # ...

    nginx:
        image: nginx:alpine
        ports: ["80:80"]
        depends_on: [php]

    db:
        image: mariadb:10.8
        volumes: [db-data:/var/lib/mysql]

volumes:
    db-data:
